version: '3'
services: 
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
  db: 
    build: containers/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    ports: 
      - "3306:3306"
  app: 
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: 
      - .:/joblink
    ports: 
      - "3000:3000"
    depends_on: 
      - chrome
      - db
    env_file: .env
    stdin_open: true
    tty: true
  web: 
    build: containers/nginx
    ports: 
      - "80:80"
    volumes: 
      - app
    depends_on: 
      - app