version: '3'
services: 
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
  db: 
    image: mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    ports: 
      - "3306:3306"
  web: 
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: 
      - .:/joblink
    ports: 
      - "3000:3000"
    depends_on: 
      - chrome
      - db
    env_file: .env
    stdin_open: true
    tty: true